[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "ec590dac30a79258c5d25f0ee7b96940fd717d0a"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "6e6c3f40238bcf232cd096d9358e21846970fa1dc5218893e2c4d42b32043c2a"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.2+0/iceberg_rust_ffi.v0.7.2.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "3cd0baf18eca568c2ce3237a7a53c69b869191c3"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "8d5a31d5d57945d04614df8ed945f22d5eac198151e8560b1869979ceafc83a6"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.2+0/iceberg_rust_ffi.v0.7.2.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "6f77538c8cc8ebf212729b8484f657a65c51f8c9"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "17e11132c7ce1fedf3239e67b97601df216e9c6c77205612c4bdcd51498e79b9"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.2+0/iceberg_rust_ffi.v0.7.2.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "f31b1f0d105b76ac29fcef11e9764b90e365a7eb"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "037962009e0167dbad7b0d6e4bb692e3bf6e1c8e61d193fa238c2fa26f3af830"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.2+0/iceberg_rust_ffi.v0.7.2.x86_64-linux-gnu.tar.gz"
