[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "899b223c1d73d9e1ddb517628f96db7c1ca099b0"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "aac8c07e46c77822254adb652bf4d66472657251c7c2248af17b5a493b3ca336"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.3.1+0/iceberg_rust_ffi.v0.3.1.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "bfb7f47ed1d06b4904fc01ad602fa8c4df63b750"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "07aba0bd9c6d27752a43646c17e1ee0082c98612926bef7f71c25bf00007c7f6"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.3.1+0/iceberg_rust_ffi.v0.3.1.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "0922bb5952a77afb0ca927f66703e6fe77699e57"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "3084ec03c12dd8a1be8785b62d8e9ba50f40e81267e61521ad8bc2c1fc4dd1f1"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.3.1+0/iceberg_rust_ffi.v0.3.1.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "2f631ba403e70af23c57884ac82abf3b52d1bf91"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "c6e3a83449087a31228a62343776cab08dcfa5ffd4c6bbcc663986e0d6a643c0"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.3.1+0/iceberg_rust_ffi.v0.3.1.x86_64-linux-gnu.tar.gz"
