[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "a41ca7b0e8165799a89abef9e492fdecba57b5af"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "4c72258374c55bb8ddd9cc4cb06dd72c175180974f52e4f9bf746360c3254176"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.2+0/iceberg_rust_ffi.v0.6.2.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "7ecc80806b8bde87cb0f33fd874d4e425dc2efff"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "c5a4a60a6e68619a88e7425d8a89d6ae50cb87022771d067f4b9c9f1afa54eb3"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.2+0/iceberg_rust_ffi.v0.6.2.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "b788000452a9eec27a2f2dc9e22d22828f2cd815"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "6b1a6c1ef89efc537fada055b217304dab7b821796a4fb7eb1c16e481d7be7b9"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.2+0/iceberg_rust_ffi.v0.6.2.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "f10c80bc68b43467dbd08c975f978ae1b2d548ea"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "8397733d4fc4ead15147958ba178b01b9a6507c59b768fdb4925319482b34122"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.2+0/iceberg_rust_ffi.v0.6.2.x86_64-linux-gnu.tar.gz"
