[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "377f226fb04c987d5f5e9e08815a960ba9058e00"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "78526464617312eb089b214864aa9b612779cbcd1d7fe4a5e4b31e0b17cbf30c"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.0+0/iceberg_rust_ffi.v0.5.0.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "e2ca2689032a9226b1ab89795bd6ae8edc2deb96"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "02f602f85974f0299e0f9cf6c4b3c82206501978f659d73bb2c7eb95fa0e2f65"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.0+0/iceberg_rust_ffi.v0.5.0.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "04ed689f504ee8494c57798648ed3c60625d23cc"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "c55693f93f0fa37b2e0b50a78708ac3e23220a45a954eb753fac81fe96dd0606"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.0+0/iceberg_rust_ffi.v0.5.0.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "10a6a95f2fcb0dc30e54be543385af6311551380"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "ec2e99078cb2f8e6153ca2997d527c554007c4b2dfc3af7850d9113e2d635e2b"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.0+0/iceberg_rust_ffi.v0.5.0.x86_64-linux-gnu.tar.gz"
