[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "0e2ec7433815dac43791b27a711b6619a2eb0669"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "ec103c343447ab47f294675208fb617845d5de572488a0ce17675b955e771971"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.0+0/iceberg_rust_ffi.v0.6.0.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "d5a61c9fefc20e4611726883296d6c5948b018f6"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "222259fe7dfeea9cf534d43374067640a63c3d07a1522e67ef484d368b470ce6"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.0+0/iceberg_rust_ffi.v0.6.0.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "1c5df136c2af014836fd97fb5e18ea43c4f3bde8"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "319b13445460ecb72252cb54d3ea287de784da108dadaed0623acb567200d53d"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.0+0/iceberg_rust_ffi.v0.6.0.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "81b192856078112cc2c84a77bf245da827252fb8"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "e33685c13ae6bc4ce5e2ceb1919c8be49a6898729181f56db5ffcaf83e0aa3a8"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.0+0/iceberg_rust_ffi.v0.6.0.x86_64-linux-gnu.tar.gz"
