[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "de3dc24e6a7749983999cc3146a4b0bedb7190a3"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "d92f59e51e0432a18f36503a3a8c6e1221e7a2b23edb1d997d84900422f84d7c"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.10+0/iceberg_rust_ffi.v0.7.10.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "d3e434d5ca3b4641ba84493786f7a4ea4814a76f"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "43d3b45d139c522ec54774939b2cdfb0fc8ba244f4b285227a3b364cc34d061b"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.10+0/iceberg_rust_ffi.v0.7.10.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "4cab27f690e71b36d4d0166cca199172af94953a"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "0f28f5b7d40495c7be9d03b1f1e834c530621d9de5eec92f66232340f1d341fd"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.10+0/iceberg_rust_ffi.v0.7.10.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "e770e8554bdccd59e510c6e06e49b4026ce15d27"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "b4c52d54ef78e73ff2886bd4b57ab3264782f88a927fce91d2544926f0eab69c"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.10+0/iceberg_rust_ffi.v0.7.10.x86_64-linux-gnu.tar.gz"
