[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "48d5a51c36dcd50d7fd4c4c3914813be85d92fe2"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "28f55c857911b88a9f6a911c85209213de66da84998d3d0dd654bc9585cb8d56"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.1+0/iceberg_rust_ffi.v0.4.1.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "5cce69fba5c3c4ac3d04c7533645b3184518083e"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "214995171b2aa2a08d5f8bc7d6b989f13364a9a796d13ad2d9dd21e3490cd248"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.1+0/iceberg_rust_ffi.v0.4.1.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "fff2a1e5149fab179949c74fdf1eee46e1141ce5"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "45f218316ce95e6ffda24f94b76fb71228cc0b0a7ed41b15f083befa2d703afc"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.1+0/iceberg_rust_ffi.v0.4.1.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "ddbf89ea63a4efca276fd79c83aa7859b29ec896"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "8c8fdd3be68e0adc3330419946875e075babfef8ec5890818e214b448829b6a5"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.1+0/iceberg_rust_ffi.v0.4.1.x86_64-linux-gnu.tar.gz"
