[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "be92dcad70c77dd9737b97a7196db7c9b2fb36b9"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "9a4a5268c8e8dc93e139aee93a45c145dda366575408b8c4110983c18c061074"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.0+0/iceberg_rust_ffi.v0.4.0.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "4e01159a01a322d9116405131aafb508a7fceaf2"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "d878219555890f5c26afe84de8b28997519d539e931b5b806861f60c68fd4dcd"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.0+0/iceberg_rust_ffi.v0.4.0.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "7b4ab377680b007ee8fd22f719f52151949a501c"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "8bd733ca1b2b685b3187281bfdb2c96d2329f1b5ae9b35ac6fc369589424db1d"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.0+0/iceberg_rust_ffi.v0.4.0.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "6c56d782540a09a99be2736581c8ae929da8296e"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "70c6501ffe6501e4b1e4f6a6ff56f0d5dbe297861e5e40f1d65ab6b6bf6021bc"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.4.0+0/iceberg_rust_ffi.v0.4.0.x86_64-linux-gnu.tar.gz"
