[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "aedd27c96df7c5469a5d0d10a0e234ddb891ce14"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "389870cf22ce2dc6d940c40be281dc66cce75ab9613c881af68a2eb4e64a5d7d"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.11+0/iceberg_rust_ffi.v0.7.11.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "dcd60f6fad569e527ef4ad108c2c134e653faa53"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "54ab5c082eb08a1dc735283ad22bbc3360c03e3d8e8267cf22f7698d7109f719"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.11+0/iceberg_rust_ffi.v0.7.11.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "a09c04994e096f2b029c5b4fbff7e204cef24695"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "dbf73e45b22fdbd75c888b97862fd043d36f5cce3926e39571a18aa86596a8c7"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.11+0/iceberg_rust_ffi.v0.7.11.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "6f196ad785afbb057a68f4eaaf500af55c3a8e9d"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "228f53c1a6e42da86eb4565d71ff7ab06348ca76e09ad4141152dd0d5b4a2d5a"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.11+0/iceberg_rust_ffi.v0.7.11.x86_64-linux-gnu.tar.gz"
