[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "3c45c791060bef11fd1d69e102ba31be99ff2f65"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "71a1bc1956b893a0919bc8932a5954e87224d015c67b88f4a5a47ba570ae0beb"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.1+0/iceberg_rust_ffi.v0.6.1.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "52b4239927b148f449dab0056c65f2232fad80bd"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "d8012530c9f491ae4a6adefc12d856587340835c5fa2607d3e605734133ef8dd"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.1+0/iceberg_rust_ffi.v0.6.1.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "332a197d1cf86556a187bbe78d55bc396bec8246"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "ba47ce09275690b7767e2602dc1bf3c080d19b8964c171d606a26b4cca6c2b92"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.1+0/iceberg_rust_ffi.v0.6.1.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "026e559a1e31c2c7d25ce6092826909f1aa79e85"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "b39b64b6d802ec71bdcab721a9867b22437f64ab7101c93b166a2ad8135e00bc"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.6.1+0/iceberg_rust_ffi.v0.6.1.x86_64-linux-gnu.tar.gz"
