[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "fd373f794dff69b1543756064ecb044d7f59ee11"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "f3ffbc915d4dac87a69aae632934e5fdc7503f2556a9cd5dae0563252bf3da42"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.9+0/iceberg_rust_ffi.v0.7.9.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "9fe587092869aad0920a9517b850b92877600849"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "5da42c66a820e8211d18fd8b02c7062912b80c126b469764617db87c3c783dcb"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.9+0/iceberg_rust_ffi.v0.7.9.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "e41de73906b0316f1d9501952594598b1ffc38cf"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "aef392a8e8e5790bab0617ab91d04dfa441b8ae0c6890d63470a625d0d2192cf"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.9+0/iceberg_rust_ffi.v0.7.9.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "958419aca99b04ed468df8f15468f34505b7c822"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "a8fc645787fa556cd41ce8a92c4d47a0c94fe849a9c5910adf89469bffc9414a"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.9+0/iceberg_rust_ffi.v0.7.9.x86_64-linux-gnu.tar.gz"
