[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "495347f6ed4facf794608db80b1a79032a07bd47"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "8e188604f2446946784758eb6a8032b99e260455a770cfb976d090662322c665"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.5+0/iceberg_rust_ffi.v0.7.5.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "b8ea688aceae04cfe9b4c844fee8db8146e2531f"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "60b69f2de56f212a51556b0747ef86f0f0e67e3f5682af6b8e30e67aa11e6e8d"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.5+0/iceberg_rust_ffi.v0.7.5.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "0e21292b50668fb9bc1c4903cd84cc40472324ad"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "6920d1f75ecb68b8bf9a76439d3076bb01fb7578968895449885b3662cc5d776"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.5+0/iceberg_rust_ffi.v0.7.5.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "3dd737d1dbb087dd0e23e0a59a1fc59e93edd34e"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "9196ff4b73820c3635d1391191ad030e966b3d04d24720eb8ae171e3631fce7f"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.5+0/iceberg_rust_ffi.v0.7.5.x86_64-linux-gnu.tar.gz"
