[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "b4e20921a81f3743f36c29bafb5611725ac8c165"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "7ca97a11cd685f520e2fc0cd372e1066793f805fcfe895d732967fea3cf9288c"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.3+0/iceberg_rust_ffi.v0.7.3.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "37b2c79cdbeed5ddc88ee2086cad980779ffcfb5"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "10d5f7ccfd13ed57cd9bdb2566ae6fbe328f98f6d26b688fba2fdc2f6a2bce60"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.3+0/iceberg_rust_ffi.v0.7.3.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "e5fae94e4f1f447c17e433a7b54fb920722b34a1"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "b81bce0873f7dd235fff9f995e119f78c7c7f13944249f8d2a0a5134220baf69"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.3+0/iceberg_rust_ffi.v0.7.3.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "14f8cb350526e8e1f3724eb52d38c1982fd57363"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "1731871a20534964e1b97edfc9cee41be2e6ff9fe31ebea365bea427fdb9f8cd"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.3+0/iceberg_rust_ffi.v0.7.3.x86_64-linux-gnu.tar.gz"
