[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "32a9a9ff564d1bcb95253198eb3fd6c3d4cca2b9"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "1acf53f2574f6f44e0df5e029c18feff31ca67924a375c1119d95b8c249f0a14"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.0+0/iceberg_rust_ffi.v0.7.0.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "91bff9a9290e87c3b058e9899e08046087b64123"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "4a32e8ce6b15997d533875470392925afa0760c8c49f1186d973e1be37128afe"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.0+0/iceberg_rust_ffi.v0.7.0.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "714d3646e411f74ecccca7858c82384641671875"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "83d656e402b8468aed843b0a808cf62025f7cdfa9bd0b7eec89c0a9e0a506aa9"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.0+0/iceberg_rust_ffi.v0.7.0.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "d945a31bd721de3909acfac517871d78e73e7067"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "dc6c7ace37fde756abfbfcca315e3fc6077e11687b96870333f5fecd12c16a81"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.0+0/iceberg_rust_ffi.v0.7.0.x86_64-linux-gnu.tar.gz"
